### ISSUE TITLE
October 31 error

### ISSUE THREAD

**Issue by djulianm** [Paul-DS/bootstrap-year-calendar#153] opened 2017-06-26 18:34 UTC
As the example shows the 31/october doesn't appears on callendar.

**Comment by William-H-M** [comment] 2017-06-26 19:05
Hi, this is a duplicate of
#142 (I know is a tooo  broad name...)
#109 
and #54 
you can see there thing related, so continue the topic either on #109 or #142 

you can close this for now, thanks.

**Closed** 2017-06-26 19:09 UTC
