### ISSUE TITLE
I could't get "modal dialog box" when i clicked date...

### ISSUE THREAD

**Issue by ahmetzeybek** [Paul-DS/bootstrap-year-calendar#107] opened 2017-02-21 21:11 UTC
Right menu works fine but when i click any date for adding event modal dialog box not opening and also Update function is not working

This is the project look please...

http://www.ahmetzeybek.com/calendar

**Comment by William-H-M** [comment] 2017-02-21 21:28
Hi, inspecting your code looks like you forgot to add this option, tough I see that deleteEvent actually works for you...
`   contextMenuItems:[
            {
                text: 'Update',
                click: editEvent
            },
            {
                text: 'Delete',
                click: deleteEvent
            }
        ],`

For more help maybe a snippet of your code will help
Good luck!

**Comment by ahmetzeybek** [comment] 2017-02-21 21:54
![screenshot_9](https://cloud.githubusercontent.com/assets/9489256/23186801/0fdd0a8c-f891-11e6-90a6-0f8a7248c83d.png)

**Comment by ahmetzeybek** [comment] 2017-02-21 21:55
I already have context menu items @William-H-M my problem is "addEvent" when i click any date i couldn't get a dialog box and clicked "Update" there is no action

**Comment by William-H-M** [comment] 2017-02-21 22:16
Hi, I've found the problem, the things is that you don't have any modal called `#event-modal` that's how it's instanciated to call the edit event or create new events you can see on the example pages on my case it do work if set the modal you can see it on [this sample page](http://copygroup-001-site2.mysitepanel.net/testcalendar.html), just create a modal with whatever name

**Comment by ahmetzeybek** [comment] 2017-02-21 23:47
Wee we solved the problem about "modal box" but now we have another problem :) We can't see our input values "name, location, dates" in calendar when we saved it check the page...

http://www.ahmetzeybek.com/calendar/

**Comment by William-H-M** [comment] 2017-02-22 01:10
Hi, sorry for the late respond just a while I go arrived home =P
The problem is in this line
`event.id = newId;
    dataSource.push(event);`
You have it like 'event' but you declared it before just as 'e'
that's why the code is not working after that it should work
Good luck!

**Comment by ahmetzeybek** [comment] 2017-02-22 01:37
Can you help more i couldn't understand, what should I do ?

**Comment by William-H-M** [comment] 2017-02-22 02:48
Sorry my bad if I didn't make myself clear
the problem is the variable `event ` is not declared or doesn't exist, so just change it like it say on the image instead of 'event.id = newId' set 'e.id = newId' and 'dataSource.push(event)' to 'dataSource.push(e)'

![captura](https://cloud.githubusercontent.com/assets/24443241/23194979/663045be-f87f-11e6-8c19-e3cec4dee505.PNG)

**Comment by ahmetzeybek** [comment] 2017-02-22 02:50
You are my hero !

**Comment by William-H-M** [comment] 2017-02-22 03:16
Great that you solved!! 🎉 🎉 🎉 🎉 🎉 🎉 
Now as this is solved close the issue maybe that way someone else with your problem later can find it easy too

**Closed** 2017-02-22 03:28 UTC
